application: google.com:angulardemo
version: 1
runtime: python27
api_version: 1
threadsafe: false

handlers:

- url: /css
  static_dir: css

- url: /components
  static_dir: components

- url: /js
  static_dir: js

- url: /lib
  static_dir: lib

- url: /img
  static_dir: img

- url: /img/icons
  static_dir: img/icons

- url: /index\.html
  static_files: index.html
  upload: index.html

- url: /favicon\.ico
  static_files: favicon.ico
  upload: favicon.ico

- url: /home\.tmpl\.html 
  static_files: home.tmpl.html
  upload: home.tmpl.html

- url: .*
  script: main.py
